version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'postgres-chill-bot'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=oli'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres-chill-bot'

  redis:
    image: 'redis'
    container_name: 'redis_dispatcher'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      #- REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    restart: unless-stopped
    #volumes:
    #  - 'redis_data:/var/lib/docker/volumes/redis_data'